name: molcalc
dependencies:
  - rdkit
  - SQLAlchemy=1.3
  - alembic
  - networkx
  - numpy
  - plaster_pastedeploy
  - pyramid
  - pyramid_debugtoolbar
  - pyramid_jinja2
  - pyramid_retry
  - pyramid_tm
  - rich
  - rmsd
  - scipy
  - tqdm
  - transaction
  - waitress
  - zope.sqlalchemy
  - jinja2=1.3
  - pip
  - pip:
    - pyramid_retry
