name: molcalc
dependencies:
  - numpy
  - scipy
  - tqdm
  - rdkit
  - SQLAlchemy=1.3
  - alembic
  - networkx
  - plaster_pastedeploy
  - pyramid
  - pyramid_debugtoolbar
  - pyramid_tm
  - rich
  - rmsd
  - transaction
  - waitress
  - jinja2=3.0
  - pip
  - pip:
    - pyramid_jinja2
    - pyramid-retry
    - zope.sqlalchemy
